word_map = {
    "backpack": "An explorer's loyal companion carried on the shoulders.",
    "balance": "The delicate art of staying steady on a tightrope.",
    "beautiful": "What remains in the eye of the beholder.",
    "blizzard": "When the world turns into a blinding wall of white.",
    "calendar": "A grid that captures the relentless march of months.",
    "challenge": "A mountain placed in your path to test your grit.",
    "committee": "A gathering of minds to decide a collective path.",
    "concentration": "The mental laser required to solve a deep mystery.",
    "confident": "Walking into a room without a shadow of doubt.",
    "consequence": "The inevitable echo that follows every action.",
    "continent": "A vast cradle of land surrounded by ancient oceans.",
    "courage": "The fire in the heart that faces fear head-on.",
    "creative": "Turning a blank canvas into a new world.",
    "curiosity": "The hunger to know what lies behind a locked door.",
    "dangerous": "A path where every step invites a hidden risk.",
    "decision": "The fork in the road where you must choose a side.",
    "development": "The slow transformation from a seed to a tree.",
    "difficulty": "A rough sea that makes a skilled sailor.",
    "discovery": "The spark of finding something the world forgot.",
    "education": "The steady lighting of a lamp in a dark room.",
    "electricity": "The invisible pulse that powers the modern age.",
    "elevator": "A vertical carriage that defies the weight of stairs.",
    "encourage": "Providing the wind beneath someone else's wings.",
    "engineer": "A master who bridges the gap between dream and machine.",
    "environment": "The living tapestry of nature that surrounds us.",
    "exaggerate": "To stretch a small fish into a giant whale in a story.",
    "excellent": "Setting a standard that others can only hope to reach.",
    "excitement": "The sudden racing of the pulse before an adventure.",
    "experience": "The wisdom gathered from the scars of many battles.",
    "fascinating": "Something so magnetic it holds your gaze for hours.",
    "flexible": "The willow tree that bows to the wind but never breaks.",
    "furniture": "The wooden soul of a room that makes it a home.",
    "generation": "A wave of people sharing the same slice of history.",
    "geography": "The silent language of maps, rivers, and mountains.",
    "government": "The organized hand that steers the ship of state.",
    "hibernate": "To retreat into a deep, dreamless winter fortress.",
    "memorable": "A moment etched forever into the walls of the mind.",
    "mischief": "The playful glint in the eye of a prankster.",
    "mystery": "A secret wrapped in a riddle and buried in time.",
    "navigate": "To find one's way using the stars or a compass.",
    "neighbor": "The one who lives just a heartbeat away across the fence.",
    "occasional": "A rare visitor that only appears every now and then.",
    "opportunity": "A golden door that only opens for a brief moment.",
    "organization": "Bringing harmony and order to a chaotic pile.",
    "passenger": "One who travels on a journey steered by another.",
    "patience": "The quiet strength to wait for the storm to pass.",
    "perfection": "A finished work where nothing can be added or taken away.",
    "phenomenon": "A rare event that leaves scientists scratching their heads.",
    "photograph": "A slice of time frozen forever in a frame.",
    "pleasant": "A gentle breeze on a warm summer afternoon.",
    "powerful": "The raw force of a lion's roar or a king's decree.",
    "pressure": "The heavy weight of expectations or deep water.",
    "priority": "The one thing that must be done before all others.",
    "problem": "A knot in the thread that requires a clever hand.",
    "process": "The methodical steps taken to reach a final goal.",
    "professional": "One who practices their craft with expert precision.",
    "quality": "The invisible stamp of excellence on a handmade tool.",
    "question": "An arrow of inquiry shot toward the target of truth.",
    "refrigerator": "A cold sanctuary that keeps the harvest fresh.",
    "remember": "To pull a ghost of the past back into the present.",
    "satellite": "A silent watcher orbiting the Earth in the void.",
    "scientist": "A seeker who questions the laws of the universe.",
    "signature": "Your unique mark on a document or a masterpiece.",
    "strategy": "The grand master's plan before the first chess move.",
    "strength": "The iron in the muscle and the steel in the will.",
    "suggestion": "A gentle seed planted in a conversation.",
    "surprise": "The sudden gasp when the unexpected arrives.",
    "technology": "The tools we build to extend the reach of our hands.",
    "temperature": "The measure of a flame's bite or ice's sting.",
    "thoughtful": "A kind gesture that considers another's silent needs.",
    "tomorrow": "The horizon of hope that we never quite reach.",
    "universe": "The endless ocean of stars, galaxies, and dark matter.",
    "unusual": "A black swan swimming in a flock of white ones.",
    "vacation": "A temporary escape from the rhythm of the clock.",
    "valuable": "Something worth more than the gold it is weighed against.",
    "weather": "The ever-changing mood of the sky above.",
    "wonderful": "Something so grand it inspires a sense of awe.",
    "abandon": "To leave someone or something behind in the cold.",
    "abundant": "A harvest so vast the barns cannot hold it all.",
    "accelerate": "To press the pedal and feel the rush of gaining speed.",
    "accurate": "Hitting the bullseye with every single shot.",
    "accustom": "To slowly grow used to a new and strange place.",
    "acknowledge": "To look a truth in the eye and admit it exists.",
    "acquire": "To add a new treasure or skill to your collection.",
    "adequate": "Just enough to get the job done, but nothing more.",
    "adjacent": "Sharing a wall or a border with a close friend.",
    "adjust": "To fine-tune a lens until the image becomes clear.",
    "advantage": "A head start that puts you in front of the pack.",
    "ambition": "The ladder you build to reach your highest dreams.",
    "amplify": "To turn up the volume until the walls begin to shake.",
    "ancestor": "A ghost from your bloodline who walked the earth before you.",
    "ancient": "Something so old the dust of centuries has buried it.",
    "anecdote": "A brief, charming tale shared over a cup of coffee.",
    "anticipate": "To feel the future arriving before it actually happens.",
    "apparent": "As clear as the sun in a cloudless sky.",
    "appendix": "An extra section added to the end of a long book.",
    "applaud": "A thunder of hands signaling a job well done.",
    "appreciate": "To truly see the worth in something others overlook.",
    "artificial": "A clever imitation that was never alive.",
    "assemble": "To bring scattered pieces together into a whole.",
    "assistance": "The helping hand offered when the load is too heavy.",
    "astronomy": "The study of the giants that burn in the deep night.",
    "atmosphere": "The thin blue veil that keeps our planet breathing.",
    "attempt": "To try with all your might, regardless of the outcome.",
    "attentive": "Watching with the focus of a hawk on a branch.",
    "authentic": "Real to the core, with no masks or lies.",
    "available": "Ready and waiting for the moment it is needed.",
    "average": "Standing right in the middle of the crowd.",
    "avoid": "To steer your ship away from the dangerous rocks.",
    "awkward": "The feeling of having two left feet at a dance.",
    "baggage": "The heavy cases we carry, both physical and mental.",
    "barrier": "A wall designed to keep the world out—or in.",
    "behavior": "The way a person acts when they think no one is looking.",
    "beneficial": "Something that nourishes and helps you grow.",
    "beverage": "A liquid relief for a dry and thirsty throat.",
    "bewildered": "Lost in a forest of confusion with no map.",
    "biology": "The grand study of everything that breathes and grows.",
    "boundary": "The invisible line where your space ends and mine begins.",
    "brief": "A flash of lightning that is over in a heartbeat.",
    "brilliant": "A mind or a light that outshines everything nearby.",
    "capacity": "The maximum amount a vessel or a mind can hold.",
    "category": "A drawer where similar things are kept together.",
    "caution": "The quiet voice that tells you to watch your step.",
    "celebrate": "To lift a glass and shout for a joyful victory.",
    "cemetery": "A quiet garden where the stories of the past sleep.",
    "century": "A long walk through ten decades of history.",
    "certainty": "A conviction as solid as the ground beneath your feet.",
    "character": "The inner metal that defines who you truly are.",
    "charity": "An act of love given to those who have nothing.",
    "chronological": "Arranging events like beads on the string of time.",
    "civilization": "The complex web of laws, art, and cities we build.",
    "clarify": "To wipe the steam off a window to see the view.",
    "classic": "Something so good it never goes out of style.",
    "collapse": "To suddenly buckle under a weight that is too heavy.",
    "collection": "A gathered group of rare or beautiful things.",
    "combination": "The secret code that brings different things together.",
    "comfort": "The warm embrace of a fire on a freezing night.",
    "community": "A group of people bound by a shared heart and home.",
    "compare": "To hold two things up to the light to see how they differ.",
    "compete": "To test your strength against a worthy rival.",
    "complete": "Placing the very last brick in a great wall.",
    "complex": "A machine with so many parts it's hard to understand.",
    "compliment": "A verbal gift that makes someone's day brighter.",
    "component": "A single cog in a much larger machine.",
    "comprehend": "To finally see the logic hidden in a difficult puzzle.",
    "compromise": "Meeting in the middle where nobody gets everything.",
    "conceal": "To wrap a secret in shadows and hide it away.",
    "concentrate": "To focus your entire being on a single point.",
    "conclude": "To write the final sentence of a long chapter.",
    "condition": "The current state of health or repair of something.",
    "confess": "To spill a secret that has been heavy on your heart.",
    "confidence": "The armor of self-belief worn into battle.",
    "confuse": "To mix up the threads until the pattern is lost.",
    "congratulate": "To share in the joy of someone else's triumph.",
    "connect": "To build a bridge between two separate worlds.",
    "conscious": "To be fully awake and aware of the world's pulse.",
    "conservation": "The duty to protect the treasures of the earth.",
    "consider": "To weigh a thought carefully in the scales of the mind.",
    "consistent": "Acting the same way, time and time again.",
    "conspicuous": "Standing out like a red coat in a field of snow.",
    "constant": "A North Star that never moves from its place.",
    "construct": "To raise a structure from the ground up.",
    "consult": "To seek the wisdom of an expert or a book.",
    "consume": "To eat, drink, or use up a resource entirely.",
    "contemporary": "Living or happening in the world right now.",
    "contribute": "To add your own drop into the collective bucket.",
    "convenient": "Something that fits perfectly into your busy life.",
    "conversation": "The rhythmic dance of words between two people.",
    "convince": "To win someone over to your way of thinking.",
    "cooperate": "To pull the oars together to move the boat forward.",
    "critical": "A moment or a comment of extreme importance.",
    "culture": "The shared songs, food, and soul of a people.",
    "curious": "The itch in the brain to find out how things work.",
    "custom": "A tradition passed down like a family heirloom.",
    "damage": "The mark left behind by a blow or an accident.",
    "debate": "A war of words fought in the arena of logic.",
    "decade": "A journey through ten years of life.",
    "deceive": "To lead someone down a path of lies and shadows.",
    "decline": "To politely say no, or to slowly fade away.",
    "decorate": "To dress a plain room in its Sunday best.",
    "decrease": "To slowly shrink in size, number, or strength.",
    "dedicate": "To give your whole heart and time to a single cause.",
    "defend": "To stand as a shield for what you believe in.",
    "definite": "Something so certain there is no room for maybe.",
    "delicate": "Something as easily broken as a butterfly's wing.",
    "demonstrate": "To show the world exactly how something is done.",
    "depart": "To turn your back on a place and start a new journey.",
    "depend": "To lean on someone else for support or survival.",
    "describe": "To paint a picture using only the colors of words.",
    "desert": "A vast, silent land of sand and extreme thirst.",
    "deserve": "To earn a reward through your own hard work.",
    "design": "The blueprint born in the mind before it is built.",
    "desire": "The burning wish for something just out of reach.",
    "destroy": "To tear something down until nothing remains.",
    "determine": "To make a firm choice that cannot be shaken.",
    "develop": "To grow and change into a better version of yourself.",
    "diagram": "A simplified map of how something works.",
    "dialogue": "The lines of speech shared by characters in a story.",
    "diamond": "A piece of coal that did well under extreme pressure.",
    "dictionary": "A silent tower where all words are kept in order.",
    "difference": "The gap between two things that are not the same.",
    "diligent": "Working with a steady and untiring hand.",
    "direction": "The compass point toward which you are traveling.",
    "disappear": "To fade into the air like smoke in the wind.",
    "disaster": "A sudden event that brings great ruin and sorrow.",
    "discipline": "The iron self-control that keeps you on the path.",
    "disclose": "To bring a secret out into the light of day.",
    "distribute": "To share a bounty among many waiting hands.",
    "diverse": "A garden filled with a thousand different flowers.",
    "divide": "To cut a whole into smaller, separate pieces.",
    "document": "A paper that holds the proof of a truth or a deal.",
    "dormant": "A sleeping volcano or a seed waiting for rain.",
    "dramatic": "Something filled with intense emotion and flair.",
    "durable": "Built so tough it can survive a thousand storms.",
    "earnest": "Speaking with a deep and honest sincerity.",
    "elaborate": "Something designed with extreme and tiny detail.",
    "elegant": "A simple, graceful beauty that needs no shouting.",
    "element": "One of the basic building blocks of the universe.",
    "eliminate": "To remove something until it is completely gone.",
    "emerge": "To step out of the shadows and into the light.",
    "emotion": "The internal weather of the human heart.",
    "emphasis": "Putting extra weight on a specific word or idea.",
    "employ": "To give someone a job and a purpose in work.",
    "enable": "To give someone the power or tools to succeed.",
    "encounter": "A sudden and unexpected meeting with a stranger.",
    "energy": "The invisible spark that makes everything move.",
    "enormous": "Something so large it dwarfs everything around it.",
    "ensure": "To take steps to make certain that something happens.",
    "entertain": "To capture an audience's heart and make them smile.",
    "entire": "The whole thing, with not a single piece missing.",
    "episode": "One small chapter in a much longer story.",
    "equal": "Perfectly balanced on the scales with no advantage.",
    "equation": "A mathematical balance where both sides must match.",
    "equipment": "The specialized tools needed for a specific task.",
    "essential": "Something you simply cannot live or succeed without.",
    "establish": "To plant a firm foundation for a new idea or city.",
    "estimate": "A thoughtful guess based on the facts at hand.",
    "eternal": "Something that has no beginning and no end.",
    "evaluate": "To judge the worth or quality of something carefully.",
    "evidence": "The footprints and clues that lead to the truth.",
    "evident": "Something so obvious it doesn't need to be explained.",
    "evolution": "The slow, ancient dance of life changing over time.",
    "examine": "To look at something through a magnifying glass.",
    "example": "A single case that shows how the rule works.",
    "exceed": "To go further than anyone expected you to go.",
    "exclude": "To close the door and leave someone outside.",
    "excursion": "A short, joyful trip away from the daily routine.",
    "exhausted": "A battery or a body that has absolutely zero fuel left.",
    "exhibit": "To put your best work on display for the world.",
    "expand": "To grow larger and take up more and more space.",
    "expect": "To wait for something you are certain will arrive.",
    "explain": "To build a bridge of understanding for someone else.",
    "explore": "To walk into the unknown just to see what is there.",
    "export": "To send your own goods out to distant lands.",
    "express": "To put your inner feelings into words or art.",
    "extend": "To reach out your hand or lengthen a deadline.",
    "exterior": "The outer shell that protects the inside of a thing.",
    "external": "Something that comes from the world outside of you.",
    "extinct": "A flame that has gone out and can never be relit.",
    "extraordinary": "Something so rare it takes your breath away.",
    "extreme": "Pushed to the very edge of what is possible.",
    "facility": "A place built for a specific and useful purpose.",
    "factor": "One of the reasons that contributes to a result.",
    "failure": "A fallen attempt that provides a lesson for next time.",
    "familiar": "A face or a place that feels like home.",
    "famous": "A name that is spoken in every corner of the world.",
    "fantastic": "Something so wonderful it feels like a dream.",
    "fashion": "The changing style of what we wear and how we look.",
    "fatigue": "The heavy bone-tiredness that follows hard work.",
    "feasible": "Something that is actually possible to achieve.",
    "feature": "A prominent part or trait that stands out.",
    "federal": "The central power that binds different states together.",
    "fertile": "Soil or a mind where ideas and life grow quickly.",
    "fiction": "A world born entirely from an author's imagination.",
    "fierce": "The intense power of a storm or a cornered tiger.",
    "final": "The very last step at the end of a long road.",
    "finance": "The complex management of money and wealth.",
    "flourish": "To grow strong and beautiful in a healthy place.",
    "focus": "To pull all your light into a single, sharp point.",
    "forbid": "To draw a line and say 'You shall not pass.'",
    "forecast": "A glimpse into what the future weather might be.",
    "foreign": "Something that belongs to a different and distant land.",
    "formal": "Dressed in your best and following strict rules.",
    "fortune": "A great pile of wealth or a lucky turn of fate.",
    "foundation": "The solid rock on which a whole building rests.",
    "fragile": "Something as easily shattered as a glass heart.",
    "frequent": "Something that happens over and over and over.",
    "frighten": "To send a sudden shiver of fear down the spine.",
    "frontier": "The edge of the known world, facing the wild.",
    "frustrate": "The feeling of hitting a wall you cannot climb.",
    "function": "The specific job that a tool was built to do.",
    "fundamental": "The basic truth that everything else is built upon.",
    "furious": "An anger so hot it burns like a wildfire.",
    "future": "The unwritten story that lies ahead of us all.",
    "abate": "When the screaming wind finally begins to die down.",
    "aberrant": "A lone traveler who has strayed far from the path.",
    "abjure": "To stand up and formally take back your old words.",
    "abscond": "To vanish into the night with the stolen treasure.",
    "abstain": "To hold back your hand when tempted by a treat.",
    "adulterate": "To spoil a pure thing by adding something cheap.",
    "aggregate": "The total sum of a thousand tiny pieces.",
    "alacrity": "The cheerful speed of someone eager to help.",
    "alleviate": "To lift a portion of someone's heavy burden.",
    "amalgamate": "To melt different metals into a single new one.",
    "ambiguous": "A signpost that points in two directions at once.",
    "ambivalent": "A heart torn between two equal and opposite choices.",
    "ameliorate": "To make a bad situation a little bit better.",
    "anachronism": "A modern watch found in an ancient tomb.",
    "analogous": "Two different things that share a similar soul.",
    "anarchy": "A world where every law has been burned away.",
    "anomalous": "The one white raven in a sky full of black ones.",
    "antipathy": "A deep and natural shudder of dislike.",
    "apathy": "A cold heart that simply does not care at all.",
    "appease": "To give the hungry giant what he wants to keep the peace.",
    "apprise": "To pull someone aside and give them the latest news.",
    "approbation": "The warm nod of a master's official approval.",
    "appropriate": "To take something for yourself without asking.",
    "arduous": "A climb so steep it drains the very soul.",
    "artless": "Natural and honest, with no hidden masks.",
    "ascetic": "One who lives in a bare room with only their thoughts.",
    "assiduous": "Working with the tireless focus of a beehive.",
    "assuage": "To pour cool water on a burning thirst or fear.",
    "attenuate": "To stretch a thick rope until it becomes a thin thread.",
    "audacious": "A move so bold it leaves the crowd breathless.",
    "austere": "A life or a room with no decorations and no luxuries.",
    "aver": "To stand tall and state a truth with total conviction.",
    "banal": "Something so common and boring it has lost its flavor.",
    "belie": "When a smile hides the true sadness in the eyes.",
    "beneficent": "An act of kindness that brings light to many.",
    "bolster": "To add a strong beam to a sagging roof.",
    "bombastic": "Using giant words to hide a very small idea.",
    "boorish": "Rude behavior that shows a lack of any manners.",
    "burgeon": "To bloom and grow with sudden, explosive life.",
    "burnish": "To rub a dull metal until it shines like a mirror.",
    "buttress": "A stone support that keeps a cathedral wall standing.",
    "cacophonous": "A wild clash of noises that hurts the ears.",
    "capricious": "Changing your mind as quickly as the wind shifts.",
    "castigation": "A severe and stinging public scolding.",
    "catalyst": "The tiny spark that starts a massive chemical fire.",
    "caustic": "A comment so sharp it burns like acid on skin.",
    "chicanery": "Using legal tricks to hide a dishonest deal.",
    "coagulate": "When a liquid begins to thicken and turn solid.",
    "coda": "The final few notes that bring a symphony to a close.",
    "cogent": "An argument so clear it’s impossible to ignore.",
    "commensurate": "A reward that perfectly matches the hard work done.",
    "compendium": "A thick book that holds all the knowledge on a subject.",
    "complaisant": "Eager to please and easy to get along with.",
    "compliant": "Following the rules without a single word of protest.",
    "conciliatory": "An olive branch offered to end an old fight.",
    "condone": "To look the other way when a wrong is done.",
    "confound": "To surprise and confuse someone completely.",
    "connoisseur": "An expert with a highly refined taste in art or wine.",
    "contentious": "Someone who loves to start an argument for no reason.",
    "conundrum": "A puzzle so difficult it seems to have no answer.",
    "converge": "When many different paths meet at a single point.",
    "convoluted": "A story so twisted it's easy to get lost in it.",
    "craven": "A heart that shrinks away in total cowardice.",
    "decorum": "The strict rules of proper behavior in high society.",
    "deference": "A respectful bow to someone with more wisdom.",
    "delineate": "To draw a sharp line to show where one thing ends.",
    "denigrate": "To try to ruin someone's good name with lies.",
    "deride": "To point and laugh with a cruel, mocking spirit.",
    "derivative": "Something that is just a copy of an older idea.",
    "desiccate": "To drain every single drop of moisture away.",
    "desultory": "Jumping from one thing to another with no plan.",
    "diatribe": "A long, angry, and bitter speech against someone.",
    "dichotomy": "A sharp division between two opposite ideas.",
    "diffidence": "A quiet shyness born from a lack of self-belief.",
    "diffuse": "Spread out so thinly that the strength is lost.",
    "digression": "Wandering off the main path of a conversation.",
    "dirge": "A slow, mournful song played at a final farewell.",
    "disabuse": "To gently correct someone's mistaken belief.",
    "discerning": "Having a sharp eye that can see the smallest details.",
    "discordant": "A jarring note that doesn't fit the harmony.",
    "discredit": "To show the world that a person or idea cannot be trusted.",
    "discrepancy": "A strange gap between two things that should match.",
    "discrete": "Entirely separate and distinct from everything else.",
    "disingenuous": "Pretending to be honest while hiding the truth.",
    "disinterested": "A judge who has no personal stake in the outcome.",
    "disjointed": "A story or a body with pieces that don't fit together.",
    "dismiss": "To wave a hand and treat an idea as unimportant.",
    "disparage": "To speak of something as if it has very little value.",
    "disparate": "Two things so different they cannot be compared.",
    "dissemble": "To put on a mask to hide your true feelings.",
    "disseminate": "To scatter seeds of information far and wide.",
    "dissolution": "The final breaking apart of a group or a bond.",
    "dissonance": "A tension between two ideas that do not fit.",
    "distend": "To swell outward from pressure within.",
    "distill": "To boil away the noise and keep only the essence.",
    "diverge": "When a single road splits into two separate paths.",
    "divest": "To strip away power, clothing, or investments.",
    "dogmatic": "Being so certain you're right that you won't listen.",
    "dupe": "To play a trick on someone who is too trusting.",
    "ebullient": "Bubbling over with an unstoppable joy.",
    "eclectic": "A collection made from the best of many different styles.",
    "efficacy": "The power of a medicine or a plan to get the job done.",
    "effrontery": "A shocking level of boldness and disrespect.",
    "elegy": "A beautiful, sad poem written for someone gone.",
    "elicit": "To skillfully draw a reaction out of a quiet person.",
    "embellish": "To add extra jewels or details to a simple story.",
    "empirical": "Truth that is found through testing and seeing.",
    "emulate": "To try to be just like someone you deeply admire.",
    "endemic": "Something found only in one specific part of the world.",
    "enervate": "To feel your strength slowly being sucked away.",
    "engender": "To give birth to a new feeling or situation.",
    "enigma": "A person or thing that is a complete mystery.",
    "enumerate": "To list things off one by one in order.",
    "ephemeral": "Something as beautiful and short-lived as a sunset.",
    "equanimity": "Staying calm and steady even in a massive storm.",
    "equivocate": "To use tricky language to avoid telling the whole truth.",
    "erudite": "Someone who has spent their whole life in books.",
    "esoteric": "Knowledge meant only for a tiny, secret group.",
    "eulogy": "A speech given to honor the life of someone passed.",
    "euphemism": "A soft word used to replace a harsh or blunt one.",
    "exacerbate": "To take a bad situation and make it much worse.",
    "exculpate": "To prove that someone is not guilty of a crime.",
    "exigency": "A sudden situation that requires immediate action.",
    "extrapolation": "Guessing what comes next based on the current pattern.",
    "facetious": "Making a joke at a time when things should be serious.",
    "facilitate": "To clear the path so that a task becomes easier.",
    "fallacious": "An argument built on a foundation of lies.",
    "fatuous": "Doing something silly or foolish with no thought.",
    "fawning": "Giving way too much praise to someone in power.",
    "felicitous": "A choice of words that is perfectly suited for the moment.",
    "fervor": "The intense heat of a deep and burning passion.",
    "flag": "To begin to lose your strength and slow down.",
    "fledgling": "A young bird or a beginner just starting to fly.",
    "flout": "To openly break a rule with no fear of the cost.",
    "foment": "To stir up trouble or start a rebellion.",
    "frugality": "The careful habit of never wasting a single cent.",
    "futile": "An effort that is destined to fail from the start.",
    "gainsay": "To stand up and deny that something is true.",
    "garrulous": "Someone who can talk your ear off for hours.",
    "goad": "To poke and prod someone until they finally take action.",
    "gregarious": "Someone who is only happy when in a large crowd.",
    "guile": "The clever, sneaky trickery of a fox.",
    "gullible": "Being so trusting you believe every tall tale.",
    "harangue": "A loud, aggressive scolding that goes on too long.",
    "homogenous": "A group where everything is exactly the same.",
    "hyperbole": "Stretching the truth until it's an obvious exaggeration.",
    "iconoclast": "One who attacks and breaks traditional beliefs.",
    "idolatry": "Worshiping something as if it were a god.",
    "immutable": "Something so solid it can never, ever be changed.",
    "impair": "To weaken or damage a sense or a skill.",
    "impassive": "A face that shows absolutely no emotion at all.",
    "impede": "To slow down progress by placing obstacles in the way.",
    "impermeable": "A surface so solid that no liquid can pass through.",
    "imperturbable": "Someone so calm they cannot be rattled by anything.",
    "impervious": "Being totally unaffected by criticism or bad weather.",
    "implacable": "An enemy who can never be calmed or satisfied.",
    "implicit": "A meaning that is understood even if not spoken.",
    "implode": "To suddenly collapse inward on yourself.",
    "inadvertently": "Doing something by accident without meaning to.",
    "inchoate": "Something that is only just beginning to take shape.",
    "incongruity": "Something that is out of place and doesn't fit in.",
    "inconsequential": "Something so small it doesn't matter at all.",
    "incorporate": "To bring many different parts into one single body.",
    "indigence": "Living in a state of extreme and grinding poverty.",
    "indolent": "Being lazy and having no desire to work.",
    "inert": "Something that has no power to move on its own.",
    "ingenuous": "Being naive, honest, and easy to trust.",
    "inherent": "A quality that is born inside of something.",
    "innocuous": "Something that looks scary but is actually harmless.",
    "insensible": "To be totally unaware or unable to feel pain.",
    "insinuate": "To suggest something bad in a very sneaky way.",
    "insipid": "Something so boring and flavorless it’s hard to enjoy.",
    "insularity": "Being narrow-minded and isolated from the world.",
    "intractable": "A problem or a person that is impossible to manage.",
    "intransigence": "A stubborn refusal to change your mind or compromise.",
    "inundate": "To overwhelm someone with a sudden flood of things.",
    "inured": "Growing tough and used to a harsh situation.",
    "invective": "A stream of abusive and insulting words.",
    "irascible": "Someone who has a very short fuse and snaps easily.",
    "irresolute": "Being unable to make up your mind and take action.",
    "itinerary": "The detailed plan for a long and exciting journey.",
    "laconic": "Using very few words to say a great deal.",
    "lassitude": "A deep physical and mental weariness.",
    "latent": "A talent or power that is hidden and waiting to emerge.",
    "laud": "To sing the praises of a hero or a great deed.",
    "lethargic": "Feeling slow, sleepy, and having no energy.",
    "levity": "Adding a bit of humor to a serious situation.",
    "loquacious": "Someone who loves the sound of their own voice.",
    "lucid": "A mind or a style of writing that is perfectly clear.",
    "magnanimous": "Being very generous and forgiving toward a rival.",
    "malleable": "Something that can be easily shaped or influenced.",
    "maverick": "An independent thinker who refuses to follow the herd.",
    "mendacious": "Someone who has a habit of telling untruths.",
    "metamorphosis": "A total and magical change from one form to another.",
    "meticulous": "Paying extreme attention to every tiny detail.",
    "misanthrope": "Someone who simply dislikes all other people.",
    "mitigate": "To take the edge off a painful or difficult situation.",
    "mollify": "To calm down someone who is very angry.",
    "morose": "Being gloomy, sullen, and having a dark mood.",
    "mundane": "The ordinary, boring parts of everyday life.",
    "negate": "To cancel out or prove that something is false.",
    "neophyte": "Someone who is brand new to a skill or a religion.",
    "obdurate": "Being stubborn and refusing to change your heart.",
    "obsequious": "Acting like a servant to win favor from a boss.",
    "obviate": "To see a problem coming and remove it early.",
    "officious": "Someone who meddles in things that aren't their business.",
}

word_list = list(word_map.keys())
